# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20170714_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='filename',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
