# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20170714_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
