# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20170714_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filename',
            name='job_id',
        ),
    ]
