# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_auto_20170714_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filename',
            name='id',
        ),
        migrations.AddField(
            model_name='filename',
            name='id1',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
